application: reaky
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  mime_type: image/x-icon

- url: /static/
  static_dir: static

- url: /.*
  script: main.py

builtins:
- datastore_admin: on
